= Stackable Public Roadmap

This repository contains the public roadmap for Stackable, a toolset/platform to add operations logic around open source software and take the headache out of using these tools in an enterprise setting.

You can find the roadmap https://github.com/stackabletech/roadmap/projects/1[here].

== Planning Horizon
We don't usually plan farther ahead than the next two/three quarters, as anything beyond that is currently not realistically foreseeable.

Anything that is not scheduled to be looked at in those quarters is gathered in the "Future" tab and will be sorted.

== Planning Meetings
We will hold quarterly roadmap meetings to allow anybody who is interested to chime in on what should be prioritized going forward.

The first meeting will be held on Feb 26th 2021 from 11:00-12:00 CET.

.The meeting will be held via Zoom:
* https://zoom.us/j/97478687959[Direct Zoom link]
* https://raw.githubusercontent.com/stackabletech/roadmap/master/roadmap-meeting-q2-2020.ics[ICS] to import into your calendar

Please drop us a line at mailto:roadmap@stackable.de[roadmap@stackable.de] if you would like to receive regular reminders for these meetings.
